# Don't write MAKEOPTS=-jX or EMERGE_DEFAULT_OPTS=-jX in make.conf, it's handled by prepare-stage1.sh script
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"

FEATURES="buildpkg"

USE="gtk gtk3 xft nls dbus networkmanager glamor udev icu"
ACCEPT_LICENSE="*"